### ISSUE TITLE
Support integration test inside a container

### ISSUE THREAD

**Issue by candysmurf** [intelsdi-x/snap-plugin-collector-rabbitmq#7]
The current integration test only supports "localhost", if RabbitMQ is inside a container or a remote server, the integration testing cannot be done without change the code. 

![screen shot 2016-07-22 at 12 17 16 pm](https://cloud.githubusercontent.com/assets/13841563/17068533/5232c1da-5006-11e6-9e28-b1b0e0bd9852.png)

**Comment by nanliu** [comment]
I'm closing this issue since we are able to run integration tests successfully in the travis ci environment. If we have a need to execute against remote rabbitmq servers, we can revisit and reopen this issue.
